hydra:
  run:
    dir: .
  output_subdir: null

data:
  dataset_name: enzymecommission
  split: structure
  split_similarity_threshold: 0.7
  data_dir: /sb/oliver_lab/data/wangx86/partoken-protein/gvp-baseline/data

model:
  node_in_dim: [6, 3]
  node_h_dim: [100, 16]
  edge_in_dim: [32, 1]
  edge_h_dim: [32, 1]
  num_layers: 3
  drop_rate: 0.1
  pooling: sum
  seq_in: false

train:
  epochs: 100
  lr: 1e-3
  batch_size: 128
  num_workers: 4
  seed: 42
  models_dir: ./saved_models
  use_wandb: true
  wandb_project: gvp-gnn-baseline
